---
title: "Covid-19"
author: "David Henderson"
date: "11/03/2020"
output: 
  html_document:
    theme: spacelab
    df_print: paged
    code_folding: hide
---

# Intro

COVID-19 plot. Code originally from @jburnmurdoch

## Libraries 

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(scales)
library(ggrepel)
options(scipen = 9)

theme_set(theme_minimal(base_size = 16, 
                        base_family = "Roboto") +
            theme(panel.grid.minor = element_blank()))
```


# Wrangle and Plot

```{r fig.width=12, fig.height=9, warning=FALSE, message=FALSE}
read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv") %>% 
  gather(date, cases, 5:ncol(.)) %>%
  mutate(date = as.Date(date, "%m/%d/%y")) %>%
  group_by(country = `Country/Region`, date) %>%
  summarise(cases = sum(cases)) %>%
  filter(country != "Others") %>%
  group_by(country) %>%
  mutate(days_since_100 = as.numeric(date-min(date[cases >= 100]))) %>%
  ungroup() %>%
  filter(is.finite(days_since_100)) %>% 
  group_by(country) %>%
  mutate(new_cases = cases-cases[days_since_100 == 0]) %>%
  filter(sum(cases >= 100) >= 5) %>%
  filter(cases >= 100) %>% 
  bind_rows(
    tibble(country = "33% daily rise", days_since_100 = 0:18) %>%
      mutate(cases = 100*1.33^days_since_100)
  ) %>%
  ungroup() %>%
  mutate(country = country %>% str_replace_all("( SAR)|( \\(.+)|(Republic of )", ""),
         country = country %>% str_replace_all("United Kingdom", "UK"),
         country = country %>% str_replace_all("Korea, South", "South Korea")) %>%
  # filter(days_since_100 <= 10) %>%
  ggplot(aes(days_since_100, cases, col = country)) +
  geom_hline(yintercept = 100) +
  geom_vline(xintercept = 0) +
  geom_line(size = 0.8) +
  geom_point(pch = 21, 
             size = 1) +
  scale_y_log10(expand = expand_scale(add = c(0,0.1)), 
                breaks=c(100, 200, 500, 1000, 2000, 5000, 10000, 100000)) +
  # scale_y_continuous(expand = expand_scale(add = c(0,100))) +
  scale_x_continuous(expand = expand_scale(add = c(0,1))) +
  theme(legend.position = "none",
        plot.margin = margin(3,15,3,3,"mm")) +
  coord_cartesian(clip = "off") +
  scale_colour_manual(values = c("UK" = "#ce3140", "US" = "#EB5E8D", "Italy" = "black", "France" = "#c2b7af",
                                 "Germany" = "#c2b7af", "Hong Kong" = "#1E8FCC", "Iran" = "#9dbf57",
                                 "Japan" = "#208fce", "Singapore" = "#1E8FCC", "South Korea" = "#208fce", 
                                 "Belgium" = "#c2b7af", "Netherlands" = "#c2b7af", "Norway" = "#c2b7af", 
                                 "Spain" = "#c2b7af", "Sweden" = "#c2b7af", "Switzerland" = "#c2b7af", 
                                 "33% daily rise" = "#D9CCC3", "Cruise Ship" = "#4477AA", "China" = "#6677CC")) +
  geom_text_repel(aes(label = paste0(" ",country)), 
                  nudge_y = 0.075,
                  data = . %>% group_by(country) %>% top_n(1, days_since_100)) +
  labs(x = "Number of days since 100th case", 
       y = "Total number of confirmed cases (logarithmic scale)",
       title = "COVID-19 outbreak",
       subtitle = "Countries with > 100 confirmed cases",
       caption = "Data from 2019 Novel Coronavirus COVID-19 (2019-nCoV) Data Repository by Johns Hopkins CSSE") -> plot_1

plot_1
```




```{r}
ggsave("plot_1.png", plot_1, width = 12, height = 9, dpi = 600)
```

